FROM ubuntu
MAINTAINER Joan David Colina <joancolina819@gmail.com>

WORKDIR /home

#Instalmos sudo
RUN apt-get update && apt-get install -y sudo
#Instalamos git
RUN yes | sudo apt-get install git
#Instalamos java
RUN sudo apt update 
RUN  yes | sudo apt install default-jdk
RUN   java -version
#Clonamos el repositorio
RUN git clone https://github.com/joancolina819/Coffee-Microservices


